[package]
name = "pbz2-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "pbz2, a parallel drop-in replacement for the bzip2 command"
readme = "../README.md"
keywords = ["bzip2", "compression", "cli", "parallel"]
categories = ["compression", "command-line-utilities"]
include = ["src", "LICENSE", "NOTICE"]

[[bin]]
name = "pbz2"
path = "src/main.rs"
doc = false

[lints]
workspace = true

[features]
default = ["simd"]
simd = ["pbz2/simd"]

[dependencies]
pbz2.workspace = true
eyre.workspace = true
lexopt.workspace = true
thiserror = { workspace = true, features = ["std"] }

[dev-dependencies]
bzip2.workspace = true
